package coid.juaracoding.pcmcucumber.util;

import java.util.Random;

public class Coretan {

    private static DataGenerator dataGenerator;

    public static String crtn;
    private static int randomFaskes;
    private static int randomKotaKTP;

    public static void main(String[] args) {
        dataGenerator = new DataGenerator();
        Random r = new Random();

        String strBlaBlaBla = "Saya yang bertanda tangan dibawah ini :\n" +
                "\n" +
                "Nama : BUDI IDRIS\n" +
                "No. Kartu Tanda Penduduk : 9525300034551324\n" +
                "Alamat : Apt. 601 JI. Gajahmada No.61, Rokan Hulu, GA 01493\n" +
                "\n" +
                "No. Kartu BPJ S Kesehatan : 9440906124606\n" +
                "\n" +
                "Bertindak untuk dan atas nama diri sendiri dengan ini menyatakan :\n" +
                "\n" +
                "1. Dengan ini setuju secara sukarela tanpa paksaan dari pihak manapun untuk memindahkan\n" +
                "alamat faskes BPJ S Kesehatan saya Siloam Clinic Siloam Clinic Bona Indah\n" +
                "\n" +
                "2. Menyerahkan dokumen—dokumen yang diperlukan sehubungan dengan pelaksanaan\n" +
                "maksud dan tujuan pada angka 1 di atas.\n" +
                "\n" +
                "3. Tidak akan melakukan keberatan dikemudian hari terhadap pemindahan faskes BPJ S\n" +
                "Kesehatan ke fakskes yang telah saya sepakati serta bertanggung jawab penuh dan\n" +
                "melepaskan Siloam Clinic atas setiap kerugian yang mungkin timbul serta kewajiban ganti\n" +
                "rugi baik langsung maupun tidak langsung atas maksud dan tujuan dari Surat Pernyataan\n" +
                "1n1.\n" +
                "\n" +
                "Demikian Surat Pernyataan ini saya buat dengan penuh tanggung jawab serta tanpa adanya\n" +
                "paksaan atupun tekanan dari pihak manapun juga.\n" +
                "\n" +
                "SURABAYA , 29 May 2024\n" +
                "\n" +
                "FALL}\n" +
                "\n" +
                "BUDI IDRIS";
        Boolean isValid = strBlaBlaBla.contains("BUDI IDRIS") && strBlaBlaBla.contains("9525300034551324") && strBlaBlaBla.contains("Apt. 601 JI. Gajahmada No.61, Rokan Hulu, GA 01493") && strBlaBlaBla.contains("9440906124606");
//        System.out.println(isValid);

        String [] kotaKTPList1={
                "KOTA JAKARTA BARAT",
                "KOTA JAKARTA PUSAT",
                "KOTA JAKARTA SELATAN",
                "KOTA JAKARTA UTARA",
                "KABUPATEN BEKASI",
                "KABUPATEN BEKASI",
                "KABUPATEN TANGERANG",
                "KABUPATEN TANGERANG",
                "KABUPATEN TANGERANG",
                "KOTA BEKASI",
                "KOTA BEKASI",
                "KOTA BEKASI",
                "KOTA BOGOR",
                "KOTA BOGOR",
                "KOTA TANGERANG",
                "KOTA TANGERANG SELATAN",
                "KOTA TANGERANG SELATAN",
                "BALI",
                "BALI",
                "BALI",
                "KOTA MEDAN",
                "KOTA PALEMBANG",
                "KOTA SURABAYA",
                "KOTA JAKARTA BARAT",};


        String [] kotaKTPList2={
                "KABUPATEN SIMEULUE","KABUPATEN ACEH SINGKIL","KABUPATEN ACEH SELATAN","KABUPATEN ACEH TENGGARA",
                "KABUPATEN ACEH TIMUR","KABUPATEN ACEH TENGAH","KABUPATEN ACEH BARAT","KABUPATEN ACEH BESAR","KABUPATEN PIDIE",
                "KABUPATEN BIREUEN","KABUPATEN ACEH UTARA",
                "KABUPATEN ACEH BARAT DAYA",
                "KABUPATEN GAYO LUES",
                "KABUPATEN ACEH TAMIANG",
                "KABUPATEN NAGAN RAYA",
                "KABUPATEN ACEH JAYA",
                "KABUPATEN BENER MERIAH",
                "KABUPATEN PIDIE JAYA",
                "KOTA BANDA ACEH",
                "KOTA SABANG",
                "KOTA LANGSA",
                "KOTA LHOKSEUMAWE",
                "KOTA SUBULUSSALAM",
                "KABUPATEN NIAS",
                "KABUPATEN MANDAILING NATAL",
                "KABUPATEN TAPANULI SELATAN",
                "KABUPATEN TAPANULI TENGAH",
                "KABUPATEN TAPANULI UTARA",
                "KABUPATEN TOBA SAMOSIR",
                "KABUPATEN LABUHAN BATU",
                "KABUPATEN ASAHAN",
                "KABUPATEN SIMALUNGUN",
                "KABUPATEN DAIRI",
                "KABUPATEN KARO",
                "KABUPATEN DELI SERDANG",
                "KABUPATEN LANGKAT",
                "KABUPATEN NIAS SELATAN",
                "KABUPATEN HUMBANG HASUNDUTAN",
                "KABUPATEN PAKPAK BHARAT",
                "KABUPATEN SAMOSIR",
                "KABUPATEN SERDANG BEDAGAI",
                "KABUPATEN BATU BARA",
                "KABUPATEN PADANG LAWAS UTARA",
                "KABUPATEN PADANG LAWAS",
                "KABUPATEN LABUHAN BATU SELATAN",
                "KABUPATEN LABUHAN BATU UTARA",
                "KABUPATEN NIAS UTARA",
                "KABUPATEN NIAS BARAT",
                "KOTA SIBOLGA",
                "KOTA TANJUNG BALAI",
                "KOTA PEMATANG SIANTAR",
                "KOTA TEBING TINGGI",
                "KOTA MEDAN",
                "KOTA BINJAI",
                "KOTA PADANGSIDIMPUAN",
                "KOTA GUNUNGSITOLI",
                "KABUPATEN KEPULAUAN MENTAWAI",
                "KABUPATEN PESISIR SELATAN",
                "KABUPATEN SOLOK",
                "KABUPATEN SIJUNJUNG",
                "KABUPATEN TANAH DATAR",
                "KABUPATEN PADANG PARIAMAN",
                "KABUPATEN AGAM",
                "KABUPATEN LIMA PULUH KOTA",
                "KABUPATEN PASAMAN",
                "KABUPATEN SOLOK SELATAN",
                "KABUPATEN DHARMASRAYA",
                "KABUPATEN PASAMAN BARAT",
                "KOTA PADANG",
                "KOTA SOLOK",
                "KOTA SAWAH LUNTO",
                "KOTA PADANG PANJANG",
                "KOTA BUKITTINGGI",
                "KOTA PAYAKUMBUH",
                "KOTA PARIAMAN",
                "KABUPATEN KUANTAN SINGINGI",
                "KABUPATEN INDRAGIRI HULU",
                "KABUPATEN INDRAGIRI HILIR",
                "KABUPATEN PELALAWAN",
                "KABUPATEN S I A K",
                "KABUPATEN KAMPAR",
                "KABUPATEN ROKAN HULU",
                "KABUPATEN BENGKALIS",
                "KABUPATEN ROKAN HILIR",
                "KABUPATEN KEPULAUAN MERANTI",
                "KOTA PEKANBARU",
                "KOTA D U M A I",
                "KABUPATEN KERINCI",
                "KABUPATEN MERANGIN",
                "KABUPATEN SAROLANGUN",
                "KABUPATEN BATANG HARI",
                "KABUPATEN MUARO JAMBI",
                "KABUPATEN TANJUNG JABUNG TIMUR",
                "KABUPATEN TANJUNG JABUNG BARAT",
                "KABUPATEN TEBO",
                "KABUPATEN BUNGO",
                "KOTA JAMBI",
                "KOTA SUNGAI PENUH",
                "KABUPATEN OGAN KOMERING ULU",
                "KABUPATEN OGAN KOMERING ILIR",
                "KABUPATEN MUARA ENIM",
                "KABUPATEN LAHAT",
                "KABUPATEN MUSI RAWAS",
                "KABUPATEN MUSI BANYUASIN",
                "KABUPATEN BANYU ASIN",
                "KABUPATEN OGAN KOMERING ULU SELATAN",
                "KABUPATEN OGAN KOMERING ULU TIMUR",
                "KABUPATEN OGAN ILIR",
                "KABUPATEN EMPAT LAWANG",
                "KABUPATEN PENUKAL ABAB LEMATANG ILIR",
                "KABUPATEN MUSI RAWAS UTARA",
                "KOTA PALEMBANG",
                "KOTA PRABUMULIH",
                "KOTA PAGAR ALAM",
                "KOTA LUBUKLINGGAU",
                "KABUPATEN BENGKULU SELATAN",
                "KABUPATEN REJANG LEBONG",
                "KABUPATEN BENGKULU UTARA",
                "KABUPATEN KAUR",
                "KABUPATEN SELUMA",
                "KABUPATEN MUKOMUKO",
                "KABUPATEN LEBONG",
                "KABUPATEN KEPAHIANG",
                "KABUPATEN BENGKULU TENGAH",
                "KOTA BENGKULU",
                "KABUPATEN LAMPUNG BARAT",
                "KABUPATEN TANGGAMUS",
                "KABUPATEN LAMPUNG SELATAN",
                "KABUPATEN LAMPUNG TIMUR",
                "KABUPATEN LAMPUNG TENGAH",
                "KABUPATEN LAMPUNG UTARA",
                "KABUPATEN WAY KANAN",
                "KABUPATEN TULANGBAWANG",
                "KABUPATEN PESAWARAN",
                "KABUPATEN PRINGSEWU",
                "KABUPATEN MESUJI",
                "KABUPATEN TULANG BAWANG BARAT",
                "KABUPATEN PESISIR BARAT",
                "KOTA BANDAR LAMPUNG",
                "KOTA METRO",
                "KABUPATEN BANGKA",
                "KABUPATEN BELITUNG",
                "KABUPATEN BANGKA BARAT",
                "KABUPATEN BANGKA TENGAH",
                "KABUPATEN BANGKA SELATAN",
                "KABUPATEN BELITUNG TIMUR",
                "KOTA PANGKAL PINANG",
                "KABUPATEN KARIMUN",
                "KABUPATEN BINTAN",
                "KABUPATEN NATUNA",
                "KABUPATEN LINGGA",
                "KABUPATEN KEPULAUAN ANAMBAS",
                "KOTA B A T A M",
                "KOTA TANJUNG PINANG",
                "KABUPATEN KEPULAUAN SERIBU",
                "KOTA JAKARTA SELATAN",
                "KOTA JAKARTA TIMUR",
                "KOTA JAKARTA PUSAT",
                "KOTA JAKARTA BARAT",
                "KOTA JAKARTA UTARA",
                "KABUPATEN BOGOR",
                "KABUPATEN SUKABUMI",
                "KABUPATEN CIANJUR",
                "KABUPATEN BANDUNG",
                "KABUPATEN GARUT",
                "KABUPATEN TASIKMALAYA",
                "KABUPATEN CIAMIS",
                "KABUPATEN KUNINGAN",
                "KABUPATEN CIREBON",
                "KABUPATEN MAJALENGKA",
                "KABUPATEN SUMEDANG",
                "KABUPATEN INDRAMAYU",
                "KABUPATEN SUBANG",
                "KABUPATEN PURWAKARTA",
                "KABUPATEN KARAWANG",
                "KABUPATEN BEKASI",
                "KABUPATEN BANDUNG BARAT",
                "KABUPATEN PANGANDARAN",
                "KOTA BOGOR",
                "KOTA SUKABUMI",
                "KOTA BANDUNG",
                "KOTA CIREBON",
                "KOTA BEKASI",
                "KOTA DEPOK",
                "KOTA CIMAHI",
                "KOTA TASIKMALAYA",
                "KOTA BANJAR",
                "KABUPATEN CILACAP",
                "KABUPATEN BANYUMAS",
                "KABUPATEN PURBALINGGA",
                "KABUPATEN BANJARNEGARA",
                "KABUPATEN KEBUMEN",
                "KABUPATEN PURWOREJO",
                "KABUPATEN WONOSOBO",
                "KABUPATEN MAGELANG",
                "KABUPATEN BOYOLALI",
                "KABUPATEN KLATEN",
                "KABUPATEN SUKOHARJO",
                "KABUPATEN WONOGIRI",
                "KABUPATEN KARANGANYAR",
                "KABUPATEN SRAGEN",
                "KABUPATEN GROBOGAN",
                "KABUPATEN BLORA",
                "KABUPATEN REMBANG",
                "KABUPATEN PATI",
                "KABUPATEN KUDUS",
                "KABUPATEN JEPARA",
                "KABUPATEN DEMAK",
                "KABUPATEN SEMARANG",
                "KABUPATEN TEMANGGUNG",
                "KABUPATEN KENDAL",
                "KABUPATEN BATANG",
                "KABUPATEN PEKALONGAN",
                "KABUPATEN PEMALANG",
                "KABUPATEN TEGAL",
                "KABUPATEN BREBES",
                "KOTA MAGELANG",
                "KOTA SURAKARTA",
                "KOTA SALATIGA",
                "KOTA SEMARANG",
                "KOTA PEKALONGAN",
                "KOTA TEGAL",
                "KABUPATEN KULON PROGO",
                "KABUPATEN BANTUL",
                "KABUPATEN GUNUNG KIDUL",
                "KABUPATEN SLEMAN",
                "KOTA YOGYAKARTA",
                "KABUPATEN PACITAN",
                "KABUPATEN PONOROGO",
                "KABUPATEN TRENGGALEK",
                "KABUPATEN TULUNGAGUNG",
                "KABUPATEN BLITAR",
                "KABUPATEN KEDIRI",
                "KABUPATEN MALANG",
                "KABUPATEN LUMAJANG",
                "KABUPATEN JEMBER",
                "KABUPATEN BANYUWANGI",
                "KABUPATEN BONDOWOSO",
                "KABUPATEN SITUBONDO",
                "KABUPATEN PROBOLINGGO",
                "KABUPATEN PASURUAN",
                "KABUPATEN SIDOARJO",
                "KABUPATEN MOJOKERTO",
                "KABUPATEN JOMBANG",
                "KABUPATEN NGANJUK",
                "KABUPATEN MADIUN",
                "KABUPATEN MAGETAN",
                "KABUPATEN NGAWI",
                "KABUPATEN BOJONEGORO",
                "KABUPATEN TUBAN",
                "KABUPATEN LAMONGAN",
                "KABUPATEN GRESIK",
                "KABUPATEN BANGKALAN",
                "KABUPATEN SAMPANG",
                "KABUPATEN PAMEKASAN",
                "KABUPATEN SUMENEP",
                "KOTA KEDIRI",
                "KOTA BLITAR",
                "KOTA MALANG",
                "KOTA PROBOLINGGO",
                "KOTA PASURUAN",
                "KOTA MOJOKERTO",
                "KOTA MADIUN",
                "KOTA SURABAYA",
                "KOTA BATU",
                "KABUPATEN PANDEGLANG",
                "KABUPATEN LEBAK",
                "KABUPATEN TANGERANG",
                "KABUPATEN SERANG",
                "KOTA TANGERANG",
                "KOTA CILEGON",
                "KOTA SERANG",
                "KOTA TANGERANG SELATAN",
                "KABUPATEN JEMBRANA",
                "KABUPATEN TABANAN",
                "KABUPATEN BADUNG",
                "KABUPATEN GIANYAR",
                "KABUPATEN KLUNGKUNG",
                "KABUPATEN BANGLI",
                "KABUPATEN KARANG ASEM",
                "KABUPATEN BULELENG",
                "KOTA DENPASAR",
                "KABUPATEN LOMBOK BARAT",
                "KABUPATEN LOMBOK TENGAH",
                "KABUPATEN LOMBOK TIMUR",
                "KABUPATEN SUMBAWA",
                "KABUPATEN DOMPU",
                "KABUPATEN BIMA",
                "KABUPATEN SUMBAWA BARAT",
                "KABUPATEN LOMBOK UTARA",
                "KOTA MATARAM",
                "KOTA BIMA",
                "KABUPATEN SUMBA BARAT",
                "KABUPATEN SUMBA TIMUR",
                "KABUPATEN KUPANG",
                "KABUPATEN TIMOR TENGAH SELATAN",
                "KABUPATEN TIMOR TENGAH UTARA",
                "KABUPATEN BELU",
                "KABUPATEN ALOR",
                "KABUPATEN LEMBATA",
                "KABUPATEN FLORES TIMUR",
                "KABUPATEN SIKKA",
                "KABUPATEN ENDE",
                "KABUPATEN NGADA",
                "KABUPATEN MANGGARAI",
                "KABUPATEN ROTE NDAO",
                "KABUPATEN MANGGARAI BARAT",
                "KABUPATEN SUMBA TENGAH",
                "KABUPATEN SUMBA BARAT DAYA",
                "KABUPATEN NAGEKEO",
                "KABUPATEN MANGGARAI TIMUR",
                "KABUPATEN SABU RAIJUA",
                "KABUPATEN MALAKA",
                "KOTA KUPANG",
                "KABUPATEN SAMBAS",
                "KABUPATEN BENGKAYANG",
                "KABUPATEN LANDAK",
                "KABUPATEN MEMPAWAH",
                "KABUPATEN SANGGAU",
                "KABUPATEN KETAPANG",
                "KABUPATEN SINTANG",
                "KABUPATEN KAPUAS HULU",
                "KABUPATEN SEKADAU",
                "KABUPATEN MELAWI",
                "KABUPATEN KAYONG UTARA",
                "KABUPATEN KUBU RAYA",
                "KOTA PONTIANAK",
                "KOTA SINGKAWANG",
                "KABUPATEN KOTAWARINGIN BARAT",
                "KABUPATEN KOTAWARINGIN TIMUR",
                "KABUPATEN KAPUAS",
                "KABUPATEN BARITO SELATAN",
                "KABUPATEN BARITO UTARA",
                "KABUPATEN SUKAMARA",
                "KABUPATEN LAMANDAU",
                "KABUPATEN SERUYAN",
                "KABUPATEN KATINGAN",
                "KABUPATEN PULANG PISAU",
                "KABUPATEN GUNUNG MAS",
                "KABUPATEN BARITO TIMUR",
                "KABUPATEN MURUNG RAYA",
                "KOTA PALANGKA RAYA",
                "KABUPATEN TANAH LAUT",
                "KABUPATEN KOTA BARU",
                "KABUPATEN BANJAR",
                "KABUPATEN BARITO KUALA",
                "KABUPATEN TAPIN",
                "KABUPATEN HULU SUNGAI SELATAN",
                "KABUPATEN HULU SUNGAI TENGAH",
                "KABUPATEN HULU SUNGAI UTARA",
                "KABUPATEN TABALONG",
                "KABUPATEN TANAH BUMBU",
                "KABUPATEN BALANGAN",
                "KOTA BANJARMASIN",
                "KOTA BANJAR BARU",
                "KABUPATEN PASER",
                "KABUPATEN KUTAI BARAT",
                "KABUPATEN KUTAI KARTANEGARA",
                "KABUPATEN KUTAI TIMUR",
                "KABUPATEN BERAU",
                "KABUPATEN PENAJAM PASER UTARA",
                "KABUPATEN MAHAKAM HULU",
                "KOTA BALIKPAPAN",
                "KOTA SAMARINDA",
                "KOTA BONTANG",
                "KABUPATEN MALINAU",
                "KABUPATEN BULUNGAN",
                "KABUPATEN TANA TIDUNG",
                "KABUPATEN NUNUKAN",
                "KOTA TARAKAN",
                "KABUPATEN BOLAANG MONGONDOW",
                "KABUPATEN MINAHASA",
                "KABUPATEN KEPULAUAN SANGIHE",
                "KABUPATEN KEPULAUAN TALAUD",
                "KABUPATEN MINAHASA SELATAN",
                "KABUPATEN MINAHASA UTARA",
                "KABUPATEN BOLAANG MONGONDOW UTARA",
                "KABUPATEN SIAU TAGULANDANG BIARO",
                "KABUPATEN MINAHASA TENGGARA",
                "KABUPATEN BOLAANG MONGONDOW SELATAN",
                "KABUPATEN BOLAANG MONGONDOW TIMUR",
                "KOTA MANADO",
                "KOTA BITUNG",
                "KOTA TOMOHON",
                "KOTA KOTAMOBAGU",
                "KABUPATEN BANGGAI KEPULAUAN",
                "KABUPATEN BANGGAI",
                "KABUPATEN MOROWALI",
                "KABUPATEN POSO",
                "KABUPATEN DONGGALA",
                "KABUPATEN TOLI-TOLI",
                "KABUPATEN BUOL",
                "KABUPATEN PARIGI MOUTONG",
                "KABUPATEN TOJO UNA-UNA",
                "KABUPATEN SIGI",
                "KABUPATEN BANGGAI LAUT",
                "KABUPATEN MOROWALI UTARA",
                "KOTA PALU",
                "KABUPATEN KEPULAUAN SELAYAR",
                "KABUPATEN BULUKUMBA",
                "KABUPATEN BANTAENG",
                "KABUPATEN JENEPONTO",
                "KABUPATEN TAKALAR",
                "KABUPATEN GOWA",
                "KABUPATEN SINJAI",
                "KABUPATEN MAROS",
                "KABUPATEN PANGKAJENE DAN KEPULAUAN",
                "KABUPATEN BARRU",
                "KABUPATEN BONE",
                "KABUPATEN SOPPENG",
                "KABUPATEN WAJO",
                "KABUPATEN SIDENRENG RAPPANG",
                "KABUPATEN PINRANG",
                "KABUPATEN ENREKANG",
                "KABUPATEN LUWU",
                "KABUPATEN TANA TORAJA",
                "KABUPATEN LUWU UTARA",
                "KABUPATEN LUWU TIMUR",
                "KABUPATEN TORAJA UTARA",
                "KOTA MAKASSAR",
                "KOTA PAREPARE",
                "KOTA PALOPO",
                "KABUPATEN BUTON",
                "KABUPATEN MUNA",
                "KABUPATEN KONAWE",
                "KABUPATEN KOLAKA",
                "KABUPATEN KONAWE SELATAN",
                "KABUPATEN BOMBANA",
                "KABUPATEN WAKATOBI",
                "KABUPATEN KOLAKA UTARA",
                "KABUPATEN BUTON UTARA",
                "KABUPATEN KONAWE UTARA",
                "KABUPATEN KOLAKA TIMUR",
                "KABUPATEN KONAWE KEPULAUAN",
                "KABUPATEN MUNA BARAT",
                "KABUPATEN BUTON TENGAH",
                "KABUPATEN BUTON SELATAN",
                "KOTA KENDARI",
                "KOTA BAUBAU",
                "KABUPATEN BOALEMO",
                "KABUPATEN GORONTALO",
                "KABUPATEN POHUWATO",
                "KABUPATEN BONE BOLANGO",
                "KABUPATEN GORONTALO UTARA",
                "KOTA GORONTALO",
                "KABUPATEN MAJENE",
                "KABUPATEN POLEWALI MANDAR",
                "KABUPATEN MAMASA",
                "KABUPATEN MAMUJU",
                "KABUPATEN MAMUJU UTARA",
                "KABUPATEN MAMUJU TENGAH",
                "KABUPATEN MALUKU TENGGARA BARAT",
                "KABUPATEN MALUKU TENGGARA",
                "KABUPATEN MALUKU TENGAH",
                "KABUPATEN BURU",
                "KABUPATEN KEPULAUAN ARU",
                "KABUPATEN SERAM BAGIAN BARAT",
                "KABUPATEN SERAM BAGIAN TIMUR",
                "KABUPATEN MALUKU BARAT DAYA",
                "KABUPATEN BURU SELATAN",
                "KOTA AMBON",
                "KOTA TUAL",
                "KABUPATEN HALMAHERA BARAT",
                "KABUPATEN HALMAHERA TENGAH",
                "KABUPATEN KEPULAUAN SULA",
                "KABUPATEN HALMAHERA SELATAN",
                "KABUPATEN HALMAHERA UTARA",
                "KABUPATEN HALMAHERA TIMUR",
                "KABUPATEN PULAU MOROTAI",
                "KABUPATEN PULAU TALIABU",
                "KOTA TERNATE",
                "KOTA TIDORE KEPULAUAN",
                "KABUPATEN FAKFAK",
                "KABUPATEN KAIMANA",
                "KABUPATEN TELUK WONDAMA",
                "KABUPATEN TELUK BINTUNI",
                "KABUPATEN MANOKWARI",
                "KABUPATEN SORONG SELATAN",
                "KABUPATEN SORONG",
                "KABUPATEN RAJA AMPAT",
                "KABUPATEN TAMBRAUW",
                "KABUPATEN MAYBRAT",
                "KABUPATEN MANOKWARI SELATAN",
                "KABUPATEN PEGUNUNGAN ARFAK",
                "KOTA SORONG",
                "KABUPATEN MERAUKE",
                "KABUPATEN JAYAWIJAYA",
                "KABUPATEN JAYAPURA",
                "KABUPATEN NABIRE",
                "KABUPATEN KEPULAUAN YAPEN",
                "KABUPATEN BIAK NUMFOR",
                "KABUPATEN PANIAI",
                "KABUPATEN PUNCAK JAYA",
                "KABUPATEN MIMIKA",
                "KABUPATEN BOVEN DIGOEL",
                "KABUPATEN MAPPI",
                "KABUPATEN ASMAT",
                "KABUPATEN YAHUKIMO",
                "KABUPATEN PEGUNUNGAN BINTANG",
                "KABUPATEN TOLIKARA",
                "KABUPATEN SARMI",
                "KABUPATEN KEEROM",
                "KABUPATEN WAROPEN",
                "KABUPATEN SUPIORI",
                "KABUPATEN MAMBERAMO RAYA",
                "KABUPATEN NDUGA",
                "KABUPATEN LANNY JAYA",
                "KABUPATEN MAMBERAMO TENGAH",
                "KABUPATEN YALIMO",
                "KABUPATEN PUNCAK",
                "KABUPATEN DOGIYAI",
                "KABUPATEN INTAN JAYA",
                "KABUPATEN DEIYAI",
                "KOTA JAYAPURA"
        };

        String [] faskesTujuanList = {
                "Siloam Clinic Meruya ",
                "Siloam Clinic Kepu Timur ",
                "Siloam Clinic Bona Indah ",
                "Siloam Clinic Sunter ",
                "Siloam Clinic Robson ",
                "Siloam Clinic Meikarta ",
                "Siloam Clinic Gading Serpong ",
                "Siloam Clinic Permata ",
                "Siloam Clinic Cisoka ",
                "Siloam Clinic Jatimakmur ",
                "Siloam Clinic Grand Galaxy ",
                "Siloam Clinic Chandra Sentosa ",
                "Siloam Clinic Bogor Selatan ",
                "Siloam Clinic Bogor Barat ",
                "Siloam Clinic Palais ",
                "Siloam Clinic Graha Raya ",
                "Siloam Clinic Pondok Cabe ",
                "Praktek Dokter Bersama dr Netty ",
                "BIMC Ubud Medical Centre ",
                "Siloam Medika Canggu ",
                "Siloam Clinic Medan ",
                "Siloam Clinic Jakabaring ",
                "Siloam Clinic Surabaya ",
                "Siloam Clinic Taman Sari ",




//                "Siloam Clinic Meruya", //|| Kota Jakarta Barat",
//                "Siloam Clinic Kepu Timur", //|| Kota Jakarta Pusat",
//                "Siloam Clinic Bona Indah", //|| Kota Jakarta Selatan",
//                "Siloam Clinic Sunter", //|| Kota Jakarta Utara",
//                "Siloam Clinic Robson", //|| Kabupaten Bekasi",
//                "Siloam Clinic Meikarta", //|| Kabupaten Bekasi",
//                "Siloam Clinic Gading Serpong",// || Kabupaten Tangerang",
//                "Siloam Clinic Permata", //|| Kabupaten Tangerang",
//                "Siloam Clinic Cisoka", //|| Kabupaten Tangerang",
//                "Siloam Clinic Jatimakmur", //|| Kota Bekasi",
//                "Siloam Clinic Grand Galaxy", //|| Kota Bekasi",
//                "Siloam Clinic Chandra Sentosa",// || Kota Bekasi",
//                "Siloam Clinic Bogor Selatan", //|| Kota Bogor",
//                "Siloam Clinic Bogor Barat", //|| Kota Bogor",
//                "Siloam Clinic Palais", //|| Kota Tangerang",
//                "Siloam Clinic Graha Raya", //|| Kota Tangerang Selatan",
//                "Siloam Clinic Pondok Cabe", //|| Kota Tangerang Selatan",
//                "Praktek Dokter Bersama dr Netty",// || Bali",
//                "BIMC Ubud Medical Centre", //|| Bali",
//                "Siloam Medika Canggu",// || Bali",
//                "Siloam Clinic Medan", //|| Kota Medan",
//                "Siloam Clinic Jakabaring",// || Kota Palembang",
//                "Siloam Clinic Surabaya", //|| Kota Surabaya",
//                "Siloam Clinic Taman Sari", //|| Kota Jakarta Barat"
        };

        int loopCount = 10;

        for (int i = 0; i < loopCount; i++) {
            // Memilih indeks secara acak
            int randomFaskes = r.nextInt(faskesTujuanList.length);
            // Menampilkan elemen yang dipilih secara acak
//            System.out.println(faskesTujuanList[randomFaskes]);
        }

        for (int i = 0; i < loopCount; i++) {
            // Memilih indeks secara acak
            int randomFaskes = r.nextInt(kotaKTPList2.length);
            // Menampilkan elemen yang dipilih secara acak
//            System.out.println(faskesTujuanList[randomFaskes]);
        }


        for (int i = 0; i < loopCount; i++) {
            // Memilih indeks secara acak
            int randomKotaKTP = r.nextInt(kotaKTPList1.length);
            // Menampilkan elemen yang dipilih secara acak
//            System.out.println(kotaKTPList[randomKotaKTP]);
        }



        System.out.println("| nama       | noBpjs        | noKtp            | alamat  | kotaKtp              | faskesAwal | faskesTujuan | alasan | fotoFaskesAwal | fotoFaskesTujuan | fotoTandaTangan |");

                DataGenerator dataGenerator = new DataGenerator(); // Pastikan ini adalah kelas yang benar untuk menghasilkan data

                for (int i = 0; i < 1; i++) {
                    System.out.println("|" + dataGenerator.dataNamaLengkap() + "|"
                            + dataGenerator.noBpjs() + "|"
                            + dataGenerator.noKtp() + "|"
                            + dataGenerator.dataAlamat() + "|"+kotaKTPList1[randomKotaKTP]+"|"
                            + dataGenerator.dataKota() + "|"+faskesTujuanList[randomFaskes]+"| Ingin Pindah|"
                            + "\\\\Foto Faskes\\\\Positif\\\\"+r.nextInt(30)+".jpeg " +
                            "| \\\\Foto Faskes\\\\Positif\\\\"+r.nextInt(30)+".jpeg " +
                            "| \\\\Foto Faskes\\\\Positif\\\\TABLEAU_SOFTWARE_LOGOjpg_Logo.jpg |");
                }
            }



}



